spring:
    profiles:
        active: @profileActive@
    application:
        name: mqtt-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




