spring:
    profiles:
        active: @profileActive@
    application:
        name: mqtt-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:18761/eureka/




