spring:
  datasource:
    url: jdbc:mysql://123.57.148.29:3306/yida1?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&useSSL=false&rewriteBatchedStatements=TRUE
    username: root
    password: iswater
    driver-class-name: com.mysql.jdbc.Driver

logging:
 config: classpath:logback-prod.xml


img:
 #文件保存路径
  uploadPath: /var/yida/
  #返回给前端的访问路径
  visitPath: /static/imgs/
  #重命名图片前缀
  prefix: etar-
   #环境地址
  imgUrl: http://123.57.148.29






