spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://123.57.148.29:3306/yida-dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=true
    username: root
    password: iswater
  jpa:
    show-sql: true
logging:
 config: classpath:logback-dev.xml

#EMQ Basic 认证
appid: 21c40690fa4e5
appsecret: Mjg1NjE0MzE1MTM3NTY0Mzc1MjI3MTg2NDA1MTc1NDU5ODE
#EMQ服务器地址
emq_server: http://39.105.103.1:8080
#接口地址
connect_url: /api/v3/connections/







