spring:
    profiles:
        active: @profileActive@
    datasource:
      type: com.zaxxer.hikari.HikariDataSource
      hikari:
        minimum-idle: 5
        maximum-pool-size: 15
        auto-commit: true
        idle-timeout: 60000
        pool-name: DatebookHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
#        生效超时
        validation-timeout: 3000
    mvc:
      static-path-pattern: /**
    application:
      name: wx-service

server:
   tomcat.max-threads: 800
   tomcat.uri-encoding: UTF-8
   tomcat:
    max-http-header-size: 10240
    max-http-post-size: 10240
   ssl:
     key-store: classpath:215072324040204.pfx
     key-store-password: 215072324040204
     key-store-type: PKCS12
   port: 443

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:18761/eureka/
feign:
  hystrix:
    enabled: true

ribbon:
  eureka:
    enabled: true
